### ISSUE TITLE
2020-05-13 Unable to install Node

### ISSUE THREAD

**Issue by Askjerry** [david-kasparov/node-red-contrib-pcf8574-cluster#9]
I have a very stock install from here: https://www.raspberrypi.org/downloads/
I installed Node Red and I also installed an ADS1115 Node without issue.
When I attempt to install your node I get an error message that the install has failed.
I cannot seem to resolve this issue, I have tried both installing from the Node Red manager and via the terminal directly with no luck. This would be a very useful NODE for me if I can get it installed.
I have started a thread at: https://discourse.nodered.org/t/pcf8574p-chip-via-i2c/26449/15

Can you assist?
Thanks,
Jerry

**Comment by MDAR** [comment]
Hi

I have a similar problem when trying to install your node set into `Node-RED 1.1.3: Maintenance Release`
With NMP Versions

```
{
  npm: '6.14.8',
  ares: '1.16.0',
  brotli: '1.0.9',
  cldr: '37.0',
  http_parser: '2.9.3',
  icu: '67.1',
  llhttp: '2.1.2',
  modules: '72',
  napi: '7',
  nghttp2: '1.41.0',
  node: '12.19.0',
  openssl: '1.1.1g',
  tz: '2019c',
  unicode: '13.0',
  uv: '1.39.0',
  v8: '7.8.279.23-node.44',
  zlib: '1.2.11'
}
```



The error log I get when trying to add your nodes via the pallet manager is this --

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--no-audit',
1 verbose cli   '--no-update-notifier',
1 verbose cli   '--no-fund',
1 verbose cli   '--save',
1 verbose cli   '--save-prefix="~"',
1 verbose cli   '--production',
1 verbose cli   'node-red-contrib-pcf8574-cluster@0.0.5'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v12.19.0
4 verbose npm-session 76cffae4bc06cf21
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/node-red-contrib-pcf8574-cluster 1052ms (from cache)
8 silly pacote version manifest for node-red-contrib-pcf8574-cluster@0.0.5 fetched in 1091ms
9 timing stage:loadCurrentTree Completed in 1294ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 2ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 79ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule node-red-contrib-pcf8574-cluster@0.0.5 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/i2c-bus 107ms (from cache)
18 silly pacote range manifest for i2c-bus@^1.2.2 fetched in 122ms
19 silly resolveWithNewModule i2c-bus@1.2.5 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/pcf8574cluster 806ms (from cache)
21 silly pacote range manifest for pcf8574cluster@^0.0.4 fetched in 818ms
22 silly resolveWithNewModule pcf8574cluster@0.0.4 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/bindings 135ms (from cache)
24 http fetch GET 304 https://registry.npmjs.org/nan 137ms (from cache)
25 silly pacote range manifest for bindings@~1.3.0 fetched in 156ms
26 silly resolveWithNewModule bindings@1.3.1 checking installable status
27 silly pacote range manifest for nan@~2.8.0 fetched in 156ms
28 silly resolveWithNewModule nan@2.8.0 checking installable status
29 http fetch GET 304 https://registry.npmjs.org/pcf8574 718ms (from cache)
30 silly pacote range manifest for pcf8574@^1.1.0 fetched in 725ms
31 silly resolveWithNewModule pcf8574@1.1.0 checking installable status
32 silly pacote range manifest for i2c-bus@^1.2.2 fetched in 16ms
33 silly resolveWithNewModule i2c-bus@1.2.5 checking installable status
34 http fetch GET 304 https://registry.npmjs.org/bluebird 103ms (from cache)
35 silly pacote range manifest for bluebird@^3.5.0 fetched in 126ms
36 silly resolveWithNewModule bluebird@3.7.2 checking installable status
37 http fetch GET 304 https://registry.npmjs.org/onoff 741ms (from cache)
38 silly pacote range manifest for onoff@^1.1.2 fetched in 753ms
39 silly resolveWithNewModule onoff@1.2.0 checking installable status
40 silly pacote range manifest for bindings@~1.3.0 fetched in 14ms
41 silly resolveWithNewModule bindings@1.3.1 checking installable status
42 silly pacote range manifest for nan@~2.8.0 fetched in 18ms
43 silly resolveWithNewModule nan@2.8.0 checking installable status
44 http fetch GET 304 https://registry.npmjs.org/epoll 80ms (from cache)
45 silly pacote range manifest for epoll@~1.0.2 fetched in 90ms
46 silly resolveWithNewModule epoll@1.0.2 checking installable status
47 silly pacote range manifest for bindings@~1.3.0 fetched in 13ms
48 silly resolveWithNewModule bindings@1.3.1 checking installable status
49 silly pacote range manifest for nan@~2.8.0 fetched in 16ms
50 silly resolveWithNewModule nan@2.8.0 checking installable status
51 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 2726ms
52 timing stage:loadIdealTree Completed in 2867ms
53 silly currentTree node-red-project@0.0.1
53 silly currentTree +-- bindings@1.5.0
53 silly currentTree +-- file-uri-to-path@1.0.0
53 silly currentTree +-- i2c-bus@5.2.0
53 silly currentTree +-- nan@2.14.1
53 silly currentTree +-- node-red-contrib-i2c@0.7.2
53 silly currentTree `-- node-red-contrib-startup-trigger@0.1.0
54 silly idealTree node-red-project@0.0.1
54 silly idealTree +-- bindings@1.5.0
54 silly idealTree +-- bluebird@3.7.2
54 silly idealTree +-- epoll@1.0.2
54 silly idealTree | +-- bindings@1.3.1
54 silly idealTree | `-- nan@2.8.0
54 silly idealTree +-- file-uri-to-path@1.0.0
54 silly idealTree +-- i2c-bus@5.2.0
54 silly idealTree +-- nan@2.14.1
54 silly idealTree +-- node-red-contrib-i2c@0.7.2
54 silly idealTree +-- node-red-contrib-pcf8574-cluster@0.0.5
54 silly idealTree | +-- bindings@1.3.1
54 silly idealTree | +-- i2c-bus@1.2.5
54 silly idealTree | `-- nan@2.8.0
54 silly idealTree +-- node-red-contrib-startup-trigger@0.1.0
54 silly idealTree +-- onoff@1.2.0
54 silly idealTree +-- pcf8574@1.1.0
54 silly idealTree | +-- bindings@1.3.1
54 silly idealTree | +-- i2c-bus@1.2.5
54 silly idealTree | `-- nan@2.8.0
54 silly idealTree `-- pcf8574cluster@0.0.4
55 silly install generateActionsToTake
56 silly diff-trees filtering actions: includeDev false includeProd true includeOpt true
57 timing stage:generateActionsToTake Completed in 41ms
58 silly diffTrees action count 14
59 silly diffTrees add bluebird@3.7.2
60 silly diffTrees add bindings@1.3.1
61 silly diffTrees add nan@2.8.0
62 silly diffTrees add epoll@1.0.2
63 silly diffTrees add bindings@1.3.1
64 silly diffTrees add nan@2.8.0
65 silly diffTrees add onoff@1.2.0
66 silly diffTrees add bindings@1.3.1
67 silly diffTrees add nan@2.8.0
68 silly diffTrees add i2c-bus@1.2.5
69 silly diffTrees add pcf8574@1.1.0
70 silly diffTrees add i2c-bus@1.2.5
71 silly diffTrees add pcf8574cluster@0.0.4
72 silly diffTrees add node-red-contrib-pcf8574-cluster@0.0.5
73 silly decomposeActions action count 112
74 silly decomposeActions fetch bluebird@3.7.2
75 silly decomposeActions extract bluebird@3.7.2
76 silly decomposeActions preinstall bluebird@3.7.2
77 silly decomposeActions build bluebird@3.7.2
78 silly decomposeActions install bluebird@3.7.2
79 silly decomposeActions postinstall bluebird@3.7.2
80 silly decomposeActions finalize bluebird@3.7.2
81 silly decomposeActions refresh-package-json bluebird@3.7.2
82 silly decomposeActions fetch bindings@1.3.1
83 silly decomposeActions extract bindings@1.3.1
84 silly decomposeActions preinstall bindings@1.3.1
85 silly decomposeActions build bindings@1.3.1
86 silly decomposeActions install bindings@1.3.1
87 silly decomposeActions postinstall bindings@1.3.1
88 silly decomposeActions finalize bindings@1.3.1
89 silly decomposeActions refresh-package-json bindings@1.3.1
90 silly decomposeActions fetch nan@2.8.0
91 silly decomposeActions extract nan@2.8.0
92 silly decomposeActions preinstall nan@2.8.0
93 silly decomposeActions build nan@2.8.0
94 silly decomposeActions install nan@2.8.0
95 silly decomposeActions postinstall nan@2.8.0
96 silly decomposeActions finalize nan@2.8.0
97 silly decomposeActions refresh-package-json nan@2.8.0
98 silly decomposeActions fetch epoll@1.0.2
99 silly decomposeActions extract epoll@1.0.2
100 silly decomposeActions preinstall epoll@1.0.2
101 silly decomposeActions build epoll@1.0.2
102 silly decomposeActions install epoll@1.0.2
103 silly decomposeActions postinstall epoll@1.0.2
104 silly decomposeActions finalize epoll@1.0.2
105 silly decomposeActions refresh-package-json epoll@1.0.2
106 silly decomposeActions fetch bindings@1.3.1
107 silly decomposeActions extract bindings@1.3.1
108 silly decomposeActions preinstall bindings@1.3.1
109 silly decomposeActions build bindings@1.3.1
110 silly decomposeActions install bindings@1.3.1
111 silly decomposeActions postinstall bindings@1.3.1
112 silly decomposeActions finalize bindings@1.3.1
113 silly decomposeActions refresh-package-json bindings@1.3.1
114 silly decomposeActions fetch nan@2.8.0
115 silly decomposeActions extract nan@2.8.0
116 silly decomposeActions preinstall nan@2.8.0
117 silly decomposeActions build nan@2.8.0
118 silly decomposeActions install nan@2.8.0
119 silly decomposeActions postinstall nan@2.8.0
120 silly decomposeActions finalize nan@2.8.0
121 silly decomposeActions refresh-package-json nan@2.8.0
122 silly decomposeActions fetch onoff@1.2.0
123 silly decomposeActions extract onoff@1.2.0
124 silly decomposeActions preinstall onoff@1.2.0
125 silly decomposeActions build onoff@1.2.0
126 silly decomposeActions install onoff@1.2.0
127 silly decomposeActions postinstall onoff@1.2.0
128 silly decomposeActions finalize onoff@1.2.0
129 silly decomposeActions refresh-package-json onoff@1.2.0
130 silly decomposeActions fetch bindings@1.3.1
131 silly decomposeActions extract bindings@1.3.1
132 silly decomposeActions preinstall bindings@1.3.1
133 silly decomposeActions build bindings@1.3.1
134 silly decomposeActions install bindings@1.3.1
135 silly decomposeActions postinstall bindings@1.3.1
136 silly decomposeActions finalize bindings@1.3.1
137 silly decomposeActions refresh-package-json bindings@1.3.1
138 silly decomposeActions fetch nan@2.8.0
139 silly decomposeActions extract nan@2.8.0
140 silly decomposeActions preinstall nan@2.8.0
141 silly decomposeActions build nan@2.8.0
142 silly decomposeActions install nan@2.8.0
143 silly decomposeActions postinstall nan@2.8.0
144 silly decomposeActions finalize nan@2.8.0
145 silly decomposeActions refresh-package-json nan@2.8.0
146 silly decomposeActions fetch i2c-bus@1.2.5
147 silly decomposeActions extract i2c-bus@1.2.5
148 silly decomposeActions preinstall i2c-bus@1.2.5
149 silly decomposeActions build i2c-bus@1.2.5
150 silly decomposeActions install i2c-bus@1.2.5
151 silly decomposeActions postinstall i2c-bus@1.2.5
152 silly decomposeActions finalize i2c-bus@1.2.5
153 silly decomposeActions refresh-package-json i2c-bus@1.2.5
154 silly decomposeActions fetch pcf8574@1.1.0
155 silly decomposeActions extract pcf8574@1.1.0
156 silly decomposeActions preinstall pcf8574@1.1.0
157 silly decomposeActions build pcf8574@1.1.0
158 silly decomposeActions install pcf8574@1.1.0
159 silly decomposeActions postinstall pcf8574@1.1.0
160 silly decomposeActions finalize pcf8574@1.1.0
161 silly decomposeActions refresh-package-json pcf8574@1.1.0
162 silly decomposeActions fetch i2c-bus@1.2.5
163 silly decomposeActions extract i2c-bus@1.2.5
164 silly decomposeActions preinstall i2c-bus@1.2.5
165 silly decomposeActions build i2c-bus@1.2.5
166 silly decomposeActions install i2c-bus@1.2.5
167 silly decomposeActions postinstall i2c-bus@1.2.5
168 silly decomposeActions finalize i2c-bus@1.2.5
169 silly decomposeActions refresh-package-json i2c-bus@1.2.5
170 silly decomposeActions fetch pcf8574cluster@0.0.4
171 silly decomposeActions extract pcf8574cluster@0.0.4
172 silly decomposeActions preinstall pcf8574cluster@0.0.4
173 silly decomposeActions build pcf8574cluster@0.0.4
174 silly decomposeActions install pcf8574cluster@0.0.4
175 silly decomposeActions postinstall pcf8574cluster@0.0.4
176 silly decomposeActions finalize pcf8574cluster@0.0.4
177 silly decomposeActions refresh-package-json pcf8574cluster@0.0.4
178 silly decomposeActions fetch node-red-contrib-pcf8574-cluster@0.0.5
179 silly decomposeActions extract node-red-contrib-pcf8574-cluster@0.0.5
180 silly decomposeActions preinstall node-red-contrib-pcf8574-cluster@0.0.5
181 silly decomposeActions build node-red-contrib-pcf8574-cluster@0.0.5
182 silly decomposeActions install node-red-contrib-pcf8574-cluster@0.0.5
183 silly decomposeActions postinstall node-red-contrib-pcf8574-cluster@0.0.5
184 silly decomposeActions finalize node-red-contrib-pcf8574-cluster@0.0.5
185 silly decomposeActions refresh-package-json node-red-contrib-pcf8574-cluster@0.0.5
186 silly install executeActions
187 silly doSerial global-install 112
188 verbose correctMkdir /root/.npm/_locks correctMkdir not in flight; initializing
189 verbose lock using /root/.npm/_locks/staging-068c4aec153704d2.lock for /root/.node-red/node_modules/.staging
190 silly doParallel extract 14
191 silly extract bluebird@3.7.2
192 silly extract bindings@1.3.1
193 silly extract nan@2.8.0
194 silly extract epoll@1.0.2
195 silly extract bindings@1.3.1
196 silly extract nan@2.8.0
197 silly extract onoff@1.2.0
198 silly extract bindings@1.3.1
199 silly extract nan@2.8.0
200 silly extract i2c-bus@1.2.5
201 silly extract pcf8574@1.1.0
202 silly extract i2c-bus@1.2.5
203 silly extract pcf8574cluster@0.0.4
204 silly extract node-red-contrib-pcf8574-cluster@0.0.5
205 silly tarball trying bluebird@^3.5.0 by hash: sha512-XpNj6GDQzdfW+r2Wnn7xiSAd7TM3jzkxGXBGTtWKuSXv1xUV+azxAm8jdWZN06QTQk+2N2XB9jRDkvbmQmcRtg==
206 silly tarball trying bindings@~1.3.0 by hash: sha512-i47mqjF9UbjxJhxGf+pZ6kSxrnI3wBLlnGI2ArWJ4r0VrvDS7ZYXkprq/pLaBWYq4GM0r4zdHY+NNRqEMU7uew==
207 silly tarball trying nan@~2.8.0 by hash: sha1-7XFfP+neArV6XmJS2QqWZ14fCFo=
208 silly tarball trying epoll@~1.0.2 by hash: sha512-3t2crZPej4v60YYvXE/pgJ62D4RZBd/UsEXsHd+H3xtDre0vO8aV9O+0ThIPlfZtHJ4vMPhz55fYK1j37rX9Ng==
209 silly tarball trying bindings@~1.3.0 by hash: sha512-i47mqjF9UbjxJhxGf+pZ6kSxrnI3wBLlnGI2ArWJ4r0VrvDS7ZYXkprq/pLaBWYq4GM0r4zdHY+NNRqEMU7uew==
210 silly tarball trying nan@~2.8.0 by hash: sha1-7XFfP+neArV6XmJS2QqWZ14fCFo=
211 silly tarball trying onoff@^1.1.2 by hash: sha512-o41qBIIs6agXRjryGBIJpq1xour69VDBfROf3IX+wiwutIowPZDcjTRCqFo+HYleiQngO1wfNqHWpjm0l0oYwQ==
212 silly tarball trying bindings@~1.3.0 by hash: sha512-i47mqjF9UbjxJhxGf+pZ6kSxrnI3wBLlnGI2ArWJ4r0VrvDS7ZYXkprq/pLaBWYq4GM0r4zdHY+NNRqEMU7uew==
213 silly tarball trying nan@~2.8.0 by hash: sha1-7XFfP+neArV6XmJS2QqWZ14fCFo=
214 silly tarball trying i2c-bus@^1.2.2 by hash: sha512-cwa0p/wg2bNx7IaCWT1aTK3Aptq3Ul2nTHHHwj8+ACfmPXsbWet5Werkzja80ZlC5sRkhIr/C0zKMmr5wJ8Z/w==
215 silly tarball trying pcf8574@^1.1.0 by hash: sha1-SvLs5ZL6M25Ry7VF6TWD1VdFxx0=
216 silly tarball trying i2c-bus@^1.2.2 by hash: sha512-cwa0p/wg2bNx7IaCWT1aTK3Aptq3Ul2nTHHHwj8+ACfmPXsbWet5Werkzja80ZlC5sRkhIr/C0zKMmr5wJ8Z/w==
217 silly tarball trying pcf8574cluster@^0.0.4 by hash: sha512-IejSfT3zIt4QtiACS8uvoxvCG0sjwxXcFzTy6eOpVd1q5hRog4U7XB/lnJUg1IijFUXY9McoaHnM7Ho0Ag4+2g==
218 silly tarball trying node-red-contrib-pcf8574-cluster@0.0.5 by hash: sha512-p2p1CBcftTGUku3tsblStFMW12/OIKhvwfBZVykApq4ZwmQQbSyVQuJEDMqc8ECOlgnfMbYUBSywObWdO6ydbA==
219 silly extract bindings@~1.3.0 extracted to /root/.node-red/node_modules/.staging/bindings-69296c51 (505ms)
220 silly extract bindings@~1.3.0 extracted to /root/.node-red/node_modules/.staging/bindings-ea9db0a5 (500ms)
221 silly extract bindings@~1.3.0 extracted to /root/.node-red/node_modules/.staging/bindings-77116be3 (495ms)
222 silly extract node-red-contrib-pcf8574-cluster@0.0.5 extracted to /root/.node-red/node_modules/.staging/node-red-contrib-pcf8574-cluster-e0f68c2a (516ms)
223 silly extract pcf8574cluster@^0.0.4 extracted to /root/.node-red/node_modules/.staging/pcf8574cluster-66fe23b9 (532ms)
224 silly extract pcf8574@^1.1.0 extracted to /root/.node-red/node_modules/.staging/pcf8574-7412741e (627ms)
225 silly extract epoll@~1.0.2 extracted to /root/.node-red/node_modules/.staging/epoll-d20017a4 (728ms)
226 silly extract onoff@^1.1.2 extracted to /root/.node-red/node_modules/.staging/onoff-87cab0a2 (765ms)
227 silly extract nan@~2.8.0 extracted to /root/.node-red/node_modules/.staging/nan-aa210c6f (938ms)
228 silly extract nan@~2.8.0 extracted to /root/.node-red/node_modules/.staging/nan-94d7abf4 (932ms)
229 silly extract nan@~2.8.0 extracted to /root/.node-red/node_modules/.staging/nan-e10f9162 (927ms)
230 silly extract bluebird@^3.5.0 extracted to /root/.node-red/node_modules/.staging/bluebird-39b6a4d6 (968ms)
231 silly extract i2c-bus@^1.2.2 extracted to /root/.node-red/node_modules/.staging/i2c-bus-81364c38 (991ms)
232 silly extract i2c-bus@^1.2.2 extracted to /root/.node-red/node_modules/.staging/i2c-bus-853b0749 (991ms)
233 timing action:extract Completed in 1023ms
234 silly doReverseSerial unbuild 112
235 silly doSerial remove 112
236 silly doSerial move 112
237 silly doSerial finalize 112
238 silly finalize /root/.node-red/node_modules/bluebird
239 silly finalize /root/.node-red/node_modules/epoll/node_modules/bindings
240 silly finalize /root/.node-red/node_modules/epoll/node_modules/nan
241 silly finalize /root/.node-red/node_modules/epoll
242 silly finalize /root/.node-red/node_modules/node-red-contrib-pcf8574-cluster/node_modules/bindings
243 silly finalize /root/.node-red/node_modules/node-red-contrib-pcf8574-cluster/node_modules/nan
244 silly finalize /root/.node-red/node_modules/onoff
245 silly finalize /root/.node-red/node_modules/pcf8574/node_modules/bindings
246 silly finalize /root/.node-red/node_modules/pcf8574/node_modules/nan
247 silly finalize /root/.node-red/node_modules/pcf8574/node_modules/i2c-bus
248 silly finalize /root/.node-red/node_modules/pcf8574
249 silly finalize /root/.node-red/node_modules/node-red-contrib-pcf8574-cluster/node_modules/i2c-bus
250 silly finalize /root/.node-red/node_modules/pcf8574cluster
251 silly finalize /root/.node-red/node_modules/node-red-contrib-pcf8574-cluster
252 timing action:finalize Completed in 121ms
253 silly doParallel refresh-package-json 14
254 silly refresh-package-json /root/.node-red/node_modules/bluebird
255 silly refresh-package-json /root/.node-red/node_modules/epoll/node_modules/bindings
256 silly refresh-package-json /root/.node-red/node_modules/epoll/node_modules/nan
257 silly refresh-package-json /root/.node-red/node_modules/epoll
258 silly refresh-package-json /root/.node-red/node_modules/node-red-contrib-pcf8574-cluster/node_modules/bindings
259 silly refresh-package-json /root/.node-red/node_modules/node-red-contrib-pcf8574-cluster/node_modules/nan
260 silly refresh-package-json /root/.node-red/node_modules/onoff
261 silly refresh-package-json /root/.node-red/node_modules/pcf8574/node_modules/bindings
262 silly refresh-package-json /root/.node-red/node_modules/pcf8574/node_modules/nan
263 silly refresh-package-json /root/.node-red/node_modules/pcf8574/node_modules/i2c-bus
264 silly refresh-package-json /root/.node-red/node_modules/pcf8574
265 silly refresh-package-json /root/.node-red/node_modules/node-red-contrib-pcf8574-cluster/node_modules/i2c-bus
266 silly refresh-package-json /root/.node-red/node_modules/pcf8574cluster
267 silly refresh-package-json /root/.node-red/node_modules/node-red-contrib-pcf8574-cluster
268 timing action:refresh-package-json Completed in 193ms
269 silly doParallel preinstall 14
270 silly preinstall bluebird@3.7.2
271 info lifecycle bluebird@3.7.2~preinstall: bluebird@3.7.2
272 silly preinstall bindings@1.3.1
273 info lifecycle bindings@1.3.1~preinstall: bindings@1.3.1
274 silly preinstall nan@2.8.0
275 info lifecycle nan@2.8.0~preinstall: nan@2.8.0
276 silly preinstall epoll@1.0.2
277 info lifecycle epoll@1.0.2~preinstall: epoll@1.0.2
278 silly preinstall bindings@1.3.1
279 info lifecycle bindings@1.3.1~preinstall: bindings@1.3.1
280 silly preinstall nan@2.8.0
281 info lifecycle nan@2.8.0~preinstall: nan@2.8.0
282 silly preinstall onoff@1.2.0
283 info lifecycle onoff@1.2.0~preinstall: onoff@1.2.0
284 silly preinstall bindings@1.3.1
285 info lifecycle bindings@1.3.1~preinstall: bindings@1.3.1
286 silly preinstall nan@2.8.0
287 info lifecycle nan@2.8.0~preinstall: nan@2.8.0
288 silly preinstall i2c-bus@1.2.5
289 info lifecycle i2c-bus@1.2.5~preinstall: i2c-bus@1.2.5
290 silly preinstall pcf8574@1.1.0
291 info lifecycle pcf8574@1.1.0~preinstall: pcf8574@1.1.0
292 silly preinstall i2c-bus@1.2.5
293 info lifecycle i2c-bus@1.2.5~preinstall: i2c-bus@1.2.5
294 silly preinstall pcf8574cluster@0.0.4
295 info lifecycle pcf8574cluster@0.0.4~preinstall: pcf8574cluster@0.0.4
296 silly preinstall node-red-contrib-pcf8574-cluster@0.0.5
297 info lifecycle node-red-contrib-pcf8574-cluster@0.0.5~preinstall: node-red-contrib-pcf8574-cluster@0.0.5
298 timing action:preinstall Completed in 14ms
299 silly doSerial build 112
300 silly build bluebird@3.7.2
301 info linkStuff bluebird@3.7.2
302 silly linkStuff bluebird@3.7.2 has /root/.node-red/node_modules as its parent node_modules
303 silly build bindings@1.3.1
304 info linkStuff bindings@1.3.1
305 silly linkStuff bindings@1.3.1 has /root/.node-red/node_modules/epoll/node_modules as its parent node_modules
306 silly build nan@2.8.0
307 info linkStuff nan@2.8.0
308 silly linkStuff nan@2.8.0 has /root/.node-red/node_modules/epoll/node_modules as its parent node_modules
309 silly build epoll@1.0.2
310 info linkStuff epoll@1.0.2
311 silly linkStuff epoll@1.0.2 has /root/.node-red/node_modules as its parent node_modules
312 silly build bindings@1.3.1
313 info linkStuff bindings@1.3.1
314 silly linkStuff bindings@1.3.1 has /root/.node-red/node_modules/node-red-contrib-pcf8574-cluster/node_modules as its parent node_modules
315 silly build nan@2.8.0
316 info linkStuff nan@2.8.0
317 silly linkStuff nan@2.8.0 has /root/.node-red/node_modules/node-red-contrib-pcf8574-cluster/node_modules as its parent node_modules
318 silly build onoff@1.2.0
319 info linkStuff onoff@1.2.0
320 silly linkStuff onoff@1.2.0 has /root/.node-red/node_modules as its parent node_modules
321 silly build bindings@1.3.1
322 info linkStuff bindings@1.3.1
323 silly linkStuff bindings@1.3.1 has /root/.node-red/node_modules/pcf8574/node_modules as its parent node_modules
324 silly build nan@2.8.0
325 info linkStuff nan@2.8.0
326 silly linkStuff nan@2.8.0 has /root/.node-red/node_modules/pcf8574/node_modules as its parent node_modules
327 silly build i2c-bus@1.2.5
328 info linkStuff i2c-bus@1.2.5
329 silly linkStuff i2c-bus@1.2.5 has /root/.node-red/node_modules/pcf8574/node_modules as its parent node_modules
330 silly build pcf8574@1.1.0
331 info linkStuff pcf8574@1.1.0
332 silly linkStuff pcf8574@1.1.0 has /root/.node-red/node_modules as its parent node_modules
333 silly build i2c-bus@1.2.5
334 info linkStuff i2c-bus@1.2.5
335 silly linkStuff i2c-bus@1.2.5 has /root/.node-red/node_modules/node-red-contrib-pcf8574-cluster/node_modules as its parent node_modules
336 silly build pcf8574cluster@0.0.4
337 info linkStuff pcf8574cluster@0.0.4
338 silly linkStuff pcf8574cluster@0.0.4 has /root/.node-red/node_modules as its parent node_modules
339 silly build node-red-contrib-pcf8574-cluster@0.0.5
340 info linkStuff node-red-contrib-pcf8574-cluster@0.0.5
341 silly linkStuff node-red-contrib-pcf8574-cluster@0.0.5 has /root/.node-red/node_modules as its parent node_modules
342 timing action:build Completed in 18ms
343 silly doSerial global-link 112
344 silly doParallel update-linked 0
345 silly doSerial install 112
346 silly install bluebird@3.7.2
347 info lifecycle bluebird@3.7.2~install: bluebird@3.7.2
348 silly install bindings@1.3.1
349 info lifecycle bindings@1.3.1~install: bindings@1.3.1
350 silly install nan@2.8.0
351 info lifecycle nan@2.8.0~install: nan@2.8.0
352 silly install epoll@1.0.2
353 info lifecycle epoll@1.0.2~install: epoll@1.0.2
354 verbose lifecycle epoll@1.0.2~install: unsafe-perm in lifecycle true
355 verbose lifecycle epoll@1.0.2~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/.node-red/node_modules/epoll/node_modules/.bin:/root/.node-red/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
356 verbose lifecycle epoll@1.0.2~install: CWD: /root/.node-red/node_modules/epoll
357 silly lifecycle epoll@1.0.2~install: Args: [ '-c', 'node-gyp rebuild' ]
358 silly lifecycle epoll@1.0.2~install: Returned: code: 1  signal: null
359 info lifecycle epoll@1.0.2~install: Failed to exec install script
360 timing action:install Completed in 5444ms
361 verbose unlock done using /root/.npm/_locks/staging-068c4aec153704d2.lock for /root/.node-red/node_modules/.staging
362 timing stage:rollbackFailedOptional Completed in 247ms
363 timing stage:runTopLevelLifecycles Completed in 11335ms
364 silly saveTree node-red-project@0.0.1
364 silly saveTree +-- node-red-contrib-i2c@0.7.2
364 silly saveTree | `-- i2c-bus@5.2.0
364 silly saveTree |   +-- bindings@1.5.0
364 silly saveTree |   | `-- file-uri-to-path@1.0.0
364 silly saveTree |   `-- nan@2.14.1
364 silly saveTree +-- node-red-contrib-pcf8574-cluster@0.0.5
364 silly saveTree | +-- i2c-bus@1.2.5
364 silly saveTree | | +-- bindings@1.3.1
364 silly saveTree | | `-- nan@2.8.0
364 silly saveTree | `-- pcf8574cluster@0.0.4
364 silly saveTree |   `-- pcf8574@1.1.0
364 silly saveTree |     +-- bluebird@3.7.2
364 silly saveTree |     +-- i2c-bus@1.2.5
364 silly saveTree |     | +-- bindings@1.3.1
364 silly saveTree |     | `-- nan@2.8.0
364 silly saveTree |     `-- onoff@1.2.0
364 silly saveTree |       `-- epoll@1.0.2
364 silly saveTree |         +-- bindings@1.3.1
364 silly saveTree |         `-- nan@2.8.0
364 silly saveTree `-- node-red-contrib-startup-trigger@0.1.0
365 verbose stack Error: epoll@1.0.2 install: `node-gyp rebuild`
365 verbose stack Exit status 1
365 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
365 verbose stack     at EventEmitter.emit (events.js:314:20)
365 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
365 verbose stack     at ChildProcess.emit (events.js:314:20)
365 verbose stack     at maybeClose (internal/child_process.js:1021:16)
365 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
366 verbose pkgid epoll@1.0.2
367 verbose cwd /root/.node-red
368 verbose Linux 3.16.85-52
369 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "--no-audit" "--no-update-notifier" "--no-fund" "--save" "--save-prefix=\"~\"" "--production" "node-red-contrib-pcf8574-cluster@0.0.5"
370 verbose node v12.19.0
371 verbose npm  v6.14.8
372 error code ELIFECYCLE
373 error errno 1
374 error epoll@1.0.2 install: `node-gyp rebuild`
374 error Exit status 1
375 error Failed at the epoll@1.0.2 install script.
375 error This is probably not a problem with npm. There is likely additional logging output above.
376 verbose exit [ 1, true ]

```
